services:
  resumetracker-api:
    image: ghcr.io/${GITHUB_REPOSITORY_OWNER}/resumetracker-api:${IMAGE_TAG:-latest}
    container_name: resumetracker-api
    restart: unless-stopped
    ports:
      - "8090:8090"
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      ConnectionStrings__DefaultConnection: ${POSTGRES_CONNECTION}
      MongoDb__ConnectionString: ${MONGO_CONNECTION}
      MongoDb__DatabaseName: ${MONGO_DATABASE}
      MongoDb__FilesCollection: resume_files
      Redis__ConnectionString: ${REDIS_CONNECTION}
      Redis__InstanceName: ${REDIS_INSTANCE}
      Jwt__SecretKey: ${JWT_SECRET}
      Jwt__Issuer: ${JWT_ISSUER}
      Jwt__Audience: ${JWT_AUDIENCE}
      Jwt__AccessTokenExpiryMinutes: ${JWT_EXPIRY_MINUTES}
      Serilog__WriteTo__0__Args__serverUrl: http://seq-logging
    volumes:
      - ~/wwwroot/resume-tracker/backend/files:/app/wwwroot/files
    networks:
      - homelab-docker-network

networks:
  homelab-docker-network:
    external: true